import { Material } from "./types";

const liquids: Material[] = [
  ["water", "Air suling", 18.015, 1, 0, 0],
  ["tap-water", "Air keran", 18.015, 1, 0, 0],
  ["ethanol", "Etanol", 46.07, 0.789, 0, 0],
  ["oil", "Minyak goreng", 880, 0.92, 0, 0],
  ["hcl01", "HCl 0,1 M", 36.46, 1, 0.1, 1],
  ["hcl1", "HCl 1 M", 36.46, 1, 1, 1],
  ["h2so4", "H₂SO₄ 0,1 M", 98.08, 1, 0.1, 2],
  ["acetic", "Cuka 0,1 M", 60.05, 1, 0.1, 0],
  ["naoh01", "NaOH 0,1 M", 40, 1, 0.1, -1],
  ["naoh1", "NaOH 1 M", 40, 1, 1, -1],
  ["ammonia", "NH₃ 0,1 M", 17.03, 1, 0.1, 0],
  ["h2o2", "H₂O₂ 3%", 34.01, 1, 0.88, 0],
].map(([id, name, mm, density, concentration, charge]) => ({
  id: String(id),
  name: String(name),
  discipline: "chemistry",
  kind: "material",
  phase: "liquid",
  molarMass: Number(mm),
  density: Number(density),
  concentration: Number(concentration),
  acid: Number(charge) > 0 ? Number(charge) : 0,
  base: Number(charge) < 0 ? -Number(charge) : 0,
  soluble: id !== "oil",
  color: id === "oil" ? "#e2bb44" : "#bde8f4",
  ka: id === "acetic" ? 1.8e-5 : undefined,
  kb: id === "ammonia" ? 1.8e-5 : undefined,
  ions: Number(charge) !== 0 ? 2 : 0,
  heatCapacity: id === "ethanol" ? 2.44 : id === "oil" ? 1.97 : 4.18,
}));

const solids: Material[] = [
  ["nacl", "NaCl", 58.44, 36, 2],
  ["kcl", "KCl", 74.55, 34, 2],
  ["cacl2", "CaCl₂", 110.98, 74, 3],
  ["licl", "LiCl", 42.39, 83, 2],
  ["na2co3", "Na₂CO₃", 105.99, 22, 3],
  ["nahco3", "NaHCO₃ / soda kue", 84.01, 10, 2],
  ["cuso4", "CuSO₄", 159.61, 32, 2],
  ["fecl3", "FeCl₃", 162.2, 92, 4],
  ["agno3", "AgNO₃", 169.87, 216, 2],
  ["bacl2", "BaCl₂", 208.23, 36, 3],
  ["pbno3", "Pb(NO₃)₂", 331.2, 52, 3],
  ["ki", "KI", 166, 144, 2],
  ["kscn", "KSCN", 97.18, 217, 2],
  ["kno3", "KNO₃", 101.1, 38, 2],
  ["na2so4", "Na₂SO₄", 142.04, 28, 3],
  ["znso4", "ZnSO₄", 161.47, 57, 2],
  ["mg", "Pita Mg", 24.31, 0, 0],
  ["zn", "Zn keping", 65.38, 0, 0],
  ["zn-powder", "Zn serbuk", 65.38, 0, 0],
  ["cu", "Kawat Cu", 63.55, 0, 0],
  ["fe", "Paku Fe", 55.85, 0, 0],
  ["al", "Al foil", 26.98, 0, 0],
  ["ag", "Ag", 107.87, 0, 0],
  ["caco3", "CaCO₃ keping", 100.09, 0, 0],
  ["caco3-powder", "CaCO₃ serbuk", 100.09, 0, 0],
  ["mno2", "MnO₂", 86.94, 0, 0],
  ["sand", "Pasir", 60.08, 0, 0],
  ["iron-powder", "Serbuk besi", 55.85, 0, 0],
  ["sucrose", "Gula pasir / sukrosa", 342.3, 200, 0],
  ["glucose", "Glukosa", 180.16, 90, 0],
  ["starch", "Amilum / tepung kanji", 162.14, 0, 0],
].map(([id, name, mm, solubility, ions]) => ({
  id: String(id),
  name: String(name),
  molarMass: Number(mm),
  discipline: "chemistry" as const,
  kind: "material" as const,
  phase: "solid" as const,
  density: 2,
  solubility: Number(solubility),
  soluble: Number(solubility) > 0,
  ions: Number(ions),
  color:
    id === "cuso4"
      ? "#3c91bc"
      : id === "fecl3"
        ? "#a76c40"
        : id === "cu"
          ? "#a86a39"
          : "#b2bcc9",
  kb: id === "na2co3" ? 2.1e-4 : undefined,
}));
const extras = [
  ["yeast", "Ragi"],
  ["protein", "Putih telur"],
  ["saliva", "Air liur / amilase"],
  ["cabbage", "Kubis ungu"],
  ["dye", "Pewarna makanan / tinta"],
  ["soap", "Sabun"],
  ["universal", "Indikator universal"],
  ["pp", "Fenolftalein"],
  ["mo", "Metil oranye"],
  ["btb", "Bromtimol biru"],
  ["litmus-red", "Lakmus merah"],
  ["litmus-blue", "Lakmus biru"],
  ["cabbage-indicator", "Ekstrak kubis ungu"],
  ["iodine", "Larutan iodin"],
  ["benedict", "Pereaksi Benedict"],
  ["biuret", "Pereaksi biuret"],
].map(([id, name]): Material => ({
  id,
  name,
  discipline: "chemistry",
  kind: "material",
  phase: "liquid",
  molarMass: 100,
  density: 1,
  color: "#bde8f4",
  tags: ["conceptual"],
}));
const containers = [
  ["beaker", "Gelas kimia", 250],
  ["test-tube", "Tabung reaksi", 25],
  ["erlenmeyer", "Labu Erlenmeyer", 250],
  ["cylinder", "Gelas ukur", 100],
  ["burette", "Buret + statif", 50],
  ["evaporating-dish", "Cawan penguap", 100],
  ["watch-glass", "Kaca arloji", 20],
  ["water-bath", "Penangas air", 500],
  ["calorimeter", "Kalorimeter", 500],
  ["aquarium", "Akuarium", 1000],
  ["incubator", "Tabung inkubasi", 100],
].map(([id, name, capacity]): Material => ({
  id: String(id),
  name: String(name),
  capacity: Number(capacity),
  kind: "container",
  discipline: ["aquarium", "incubator"].includes(String(id))
    ? "biology"
    : "chemistry",
  color: "#bde8f4",
}));
const tools: [string, string, string][] = [
  ["dropper", "Pipet tetes", "transfer"],
  ["rack", "Rak tabung reaksi", "support"],
  ["funnel", "Corong + kertas saring", "filter"],
  ["stirrer", "Batang pengaduk", "stir"],
  ["burner", "Pembakar virtual", "heat"],
  ["tripod", "Kaki tiga + kasa", "support"],
  ["thermometer", "Termometer", "temperature"],
  ["balance", "Timbangan digital", "mass"],
  ["ph-meter", "pH meter", "ph"],
  ["stopwatch", "Stopwatch", "time"],
  ["electrolyte-tester", "Uji elektrolit", "conductivity"],
  ["electrolysis", "Sel elektrolisis", "electrolysis"],
  ["chromatography", "Kertas kromatografi", "chromatography"],
  ["balloon", "Balon", "gas"],
];
const physics: [string, string, string][] = [
  ["block", "Balok", "incline"],
  ["ball", "Bola", "fall"],
  ["cart", "Troli dinamik", "newton"],
  ["incline", "Bidang miring", "incline"],
  ["pulley", "Katrol + tali", "newton"],
  ["spring", "Pegas", "spring"],
  ["pendulum", "Bandul", "pendulum"],
  ["spring-balance", "Neraca pegas", "buoyancy"],
  ["ruler", "Mistar", "length"],
  ["launcher", "Meriam proyektil", "projectile"],
  ["surface", "Meja licin / kasar / karpet", "friction"],
  ["fluid-vessel", "Bejana fluida", "buoyancy"],
  ["wood", "Kayu", "buoyancy"],
  ["ice", "Es", "phase"],
  ["iron", "Besi", "buoyancy"],
  ["aluminium", "Aluminium", "buoyancy"],
  ["copper", "Tembaga", "buoyancy"],
  ["plastic", "Plastik", "buoyancy"],
  ["cork", "Gabus", "buoyancy"],
  ["heater", "Pemanas listrik", "heat"],
  ["communicating-vessels", "Bejana berhubungan", "hydrostatic"],
  ["u-tube", "Pipa U", "hydrostatic"],
  ["battery", "Baterai / catu daya", "circuit"],
  ["lamp", "Lampu pijar", "circuit"],
  ["resistor", "Resistor", "circuit"],
  ["switch", "Saklar", "circuit"],
  ["wire", "Kabel", "circuit"],
  ["fuse", "Sekring", "circuit"],
  ["ammeter", "Amperemeter", "current"],
  ["voltmeter", "Voltmeter", "voltage"],
  ["multimeter", "Multimeter", "current"],
  ["capacitor", "Kapasitor", "rc"],
  ["led", "LED", "led"],
  ["rheostat", "Rheostat", "circuit"],
  ["magnet", "Magnet batang", "magnet"],
  ["coil", "Kumparan", "induction"],
  ["compass", "Kompas", "magnet"],
  ["galvanometer", "Galvanometer", "induction"],
  ["light", "Sumber cahaya", "snell"],
  ["screen", "Layar", "lens"],
  ["convex-lens", "Lensa cembung", "lens"],
  ["concave-lens", "Lensa cekung", "lens"],
  ["plane-mirror", "Cermin datar", "reflection"],
  ["concave-mirror", "Cermin cekung", "lens"],
  ["convex-mirror", "Cermin cembung", "lens"],
  ["prism", "Prisma kaca", "dispersion"],
  ["glass-block", "Balok kaca / air", "snell"],
  ["slit", "Celah", "wave"],
  ["slinky", "Tali / slinky", "wave"],
  ["tuning-fork", "Garpu tala", "sound"],
  ["sound-source", "Sumber bunyi", "sound"],
  ["oscilloscope", "Osiloskop", "wave"],
  ["collision", "Dua troli tumbukan", "collision"],
  ["metal-rod", "Batang pemuaian", "expansion"],
  ["black-white", "Permukaan hitam / putih", "radiation"],
];
const biology: [string, string, string][] = [
  ["microscope", "Mikroskop", "microscope"],
  ["slide", "Kaca objek + penutup", "support"],
  ["tweezers", "Pinset", "support"],
  ["razor", "Silet virtual", "support"],
  ["methylene", "Metilen biru", "stain"],
  ["onion", "Epidermis bawang", "microscope"],
  ["cheek", "Sel pipi", "microscope"],
  ["elodea", "Daun Elodea", "photosynthesis"],
  ["paramecium", "Paramecium", "microscope"],
  ["yeast-slide", "Preparat ragi", "microscope"],
  ["stomata", "Epidermis daun / stomata", "microscope"],
  ["blood", "Preparat sel darah", "microscope"],
  ["potato", "Kentang", "osmosis"],
  ["salt-solution", "Larutan garam", "osmosis"],
  ["sugar-solution", "Larutan gula", "osmosis"],
  ["grow-light", "Lampu tumbuhan", "photosynthesis"],
  ["liver", "Hati segar", "catalase"],
  ["boiled-liver", "Hati direbus", "catalase"],
  ["seed", "Biji kacang / kecambah", "growth"],
  ["dark-box", "Kotak gelap", "growth"],
  ["transpiration-bag", "Kantong transpirasi", "transpiration"],
  ["potometer", "Potometer", "transpiration"],
  ["fan", "Kipas", "transpiration"],
  ["punnett", "Papan Punnett", "genetics"],
  ["fish", "Ikan virtual", "ecosystem"],
  ["feed", "Pakan", "ecosystem"],
  ["rice", "Nasi", "food"],
  ["bread", "Roti", "food"],
  ["milk", "Susu", "food"],
  ["egg", "Telur", "food"],
  ["apple", "Apel", "food"],
  ["soil", "Tanah", "soil"],
];
const productData: Material[] = [
  {
    id: "acetate",
    name: "Natrium asetat",
    soluble: true,
    kind: "material",
    discipline: "chemistry",
    molarMass: 82.03,
    base: 1,
    ka: 1.8e-5,
    ions: 2,
  },
  {
    id: "ammonium",
    name: "Amonium klorida",
    soluble: true,
    kind: "material",
    discipline: "chemistry",
    molarMass: 53.49,
    acid: 1,
    kb: 1.8e-5,
    ions: 2,
  },
  ...[
    ["agcl", 143.32],
    ["baso4", 233.39],
    ["pbi2", 461],
    ["cuoh2", 97.56],
    ["feoh3", 106.87],
    ["agi", 234.77],
    ["pbcl2", 278.1],
    ["mgo", 40.3],
    ["fe-copper-salt", 151.9],
    ["h2", 2.016],
    ["o2", 32],
    ["co2", 44.01],
  ].map(([id, m]): Material => ({
    id: String(id),
    name: String(id),
    molarMass: Number(m),
    kind: "material",
    discipline: "chemistry",
    phase: ["h2", "o2", "co2"].includes(String(id)) ? "gas" : "solid",
  })),
].map((x) => ({ ...x, kind: "material", discipline: "chemistry" }) as Material);
export const catalog: Material[] = [
  ...liquids,
  ...solids,
  ...extras,
  ...containers,
  ...tools.map(([id, name, model]): Material => ({
    id,
    name,
    model,
    kind: ["temperature", "mass", "ph", "time", "conductivity"].includes(model)
      ? "instrument"
      : "apparatus",
    discipline: "chemistry",
  })),
  ...physics.map(([id, name, model]): Material => ({
    id,
    name,
    model,
    kind: ["current", "voltage", "length"].includes(model)
      ? "instrument"
      : "apparatus",
    discipline: "physics",
  })),
  ...biology.map(([id, name, model]): Material => ({
    id,
    name,
    model,
    kind: "apparatus",
    discipline: "biology",
  })),
];
export const materials = Object.fromEntries(
  [...catalog, ...productData].map((m) => [m.id, m]),
);
export const specimens: Record<
  string,
  {
    name: string;
    shape: "plant" | "animal" | "blood" | "stomata" | "yeast" | "ciliate";
    structures: string[];
  }
> = {
  onion: {
    name: "Epidermis bawang",
    shape: "plant",
    structures: ["dinding sel", "sitoplasma", "inti", "vakuola"],
  },
  cheek: {
    name: "Sel pipi",
    shape: "animal",
    structures: ["membran", "sitoplasma", "inti"],
  },
  elodea: {
    name: "Elodea",
    shape: "plant",
    structures: ["dinding sel", "vakuola", "kloroplas"],
  },
  paramecium: {
    name: "Paramecium",
    shape: "ciliate",
    structures: ["silia", "inti", "vakuola"],
  },
  "yeast-slide": {
    name: "Ragi",
    shape: "yeast",
    structures: ["dinding sel", "tunas"],
  },
  stomata: {
    name: "Stomata",
    shape: "stomata",
    structures: ["sel penjaga", "celah stomata"],
  },
  blood: {
    name: "Apusan darah",
    shape: "blood",
    structures: ["eritrosit", "leukosit", "trombosit"],
  },
};
export const defaultParams = (material: Material): Record<string, number> => ({
  paperLength: 80,
  rf1: 0.2,
  rf2: 0.5,
  rf3: 0.8,
  amount: material.phase === "solid" ? 1 : 10,
  mass: 1,
  voltage: 6,
  resistance: 100,
  angle: 30,
  speed: 10,
  length: 1,
  spring: 100,
  friction: 0.2,
  force: 5,
  restitution: 1,
  mass2: 1,
  speed2: 0,
  fluidDensity: 1000,
  density:
    material.id === "wood"
      ? 600
      : material.id === "cork"
        ? 240
        : material.id === "ice"
          ? 917
          : material.id === "plastic"
            ? 1050
            : material.id === "aluminium"
              ? 2700
              : material.id === "copper"
                ? 8960
                : 7800,
  depth: 0.5,
  power: 100,
  focus: 0,
  magnification: 40,
  light: 100,
  concentration: 0.1,
  wind: 0,
  humidity: 50,
  n1: 1,
  n2: 1.5,
  focal:
    material.id === "concave-lens" || material.id === "convex-mirror"
      ? -0.2
      : 0.2,
  distance: 0.4,
  frequency: 5,
  wavelength: 1,
  capacitance: 0.001,
  turns: 100,
  motion: 0,
  polarity: 1,
  topology: 0,
  amplitude: 10,
  ph: 7,
  water: 1,
  fish: 2,
  plants: 3,
  feed: 1,
  seed: 42,
  genotype: 0,
  time: 0,
});
