import type { Rule } from "../../domain/types";

const physical: [string, string, string][] = [
  ["incline", "incline", "Gerak bidang miring"],
  ["static-friction", "friction", "Gaya gesek statis"],
  ["fall", "fall", "Jatuh bebas"],
  ["projectile", "projectile", "Gerak parabola"],
  ["newton", "newton", "Troli dan beban katrol"],
  ["hooke", "spring", "Hukum Hooke"],
  ["spring-series", "spring", "Pegas seri"],
  ["spring-parallel", "spring", "Pegas paralel"],
  ["spring-oscillation", "spring", "Osilasi pegas"],
  ["pendulum", "pendulum", "Bandul sederhana"],
  ["collision", "collision", "Tumbukan troli"],
  ["energy", "incline", "Usaha dan energi"],
  ["buoyancy", "buoyancy", "Archimedes"],
  ["hydrostatic", "hydrostatic", "Tekanan hidrostatik"],
  ["pascal", "hydrostatic", "Pipa U dan Pascal"],
  ["heating", "heat", "Kalor jenis"],
  ["phase", "phase", "Kalor laten es dan air"],
  ["calorimetry", "heat", "Asas Black"],
  ["expansion", "expansion", "Pemuaian"],
  ["conduction", "expansion", "Konduksi dan konveksi konseptual"],
  ["radiation", "radiation", "Radiasi"],
  ["ohm", "circuit", "Hukum Ohm"],
  ["series", "circuit", "Rangkaian seri"],
  ["parallel", "circuit", "Rangkaian paralel"],
  ["short", "circuit", "Korsleting / sekring"],
  ["power", "circuit", "Daya dan energi"],
  ["rc", "rc", "Pengisian RC"],
  ["led", "led", "Polaritas LED"],
  ["magnet", "magnet", "Kutub magnet"],
  ["electromagnet", "induction", "Elektromagnet"],
  ["induction", "induction", "Induksi"],
  ["reflection", "reflection", "Pemantulan"],
  ["snell", "snell", "Pembiasan Snell"],
  ["tir", "snell", "Pemantulan sempurna"],
  ["lens", "lens", "Bayangan lensa / cermin"],
  ["telescope", "lens", "Dua lensa"],
  ["dispersion", "dispersion", "Prisma"],
  ["wave", "wave", "Gelombang tali"],
  ["standing-wave", "wave", "Gelombang berdiri"],
  ["sound", "sound", "Resonansi bunyi"],
  ["doppler", "sound", "Doppler"],
];
export const physicsRules: Rule[] = physical.map(([id, model, label]) => ({
  id: `physics-${id}`,
  label,
  discipline: "physics",
  trigger: [],
  model: `physics:${model}`,
  event: "instrument.read",
  observation: "Nilai alat ukur berubah sesuai kondisi.",
}));
