import { chemistryMaterials } from "./catalog";
import type { EquipmentGuide } from "../../lib/sandbox/equipmentGuides";

const descriptions: Record<string, string> = {
  water: "Air suling menjadi pelarut dan pembanding saat mengencerkan larutan.",
  "tap-water": "Air keran menjadi pembanding air suling. Kandungan mineral nyata berbeda menurut sumbernya; model ini tidak merepresentasikan sampel air daerahmu.",
  ethanol: "Etanol adalah pelarut untuk membandingkan pelarutan dan pemisahan dengan air. Etanol nyata mudah terbakar.",
  oil: "Minyak tidak bercampur merata dengan air. Bandingkan lapisan sebelum dan sesudah memakai sabun atau mengaduk.",
  hcl01: "HCl 0,1 M adalah larutan asam kuat. Bandingkan pH dan warna indikator sebelum dan sesudah pengenceran.",
  hcl1: "HCl 1 M lebih pekat daripada HCl 0,1 M. Bandingkan kedua larutan dengan volume sama, lalu amati pengaruh pengenceran.",
  h2so4: "H₂SO₄ adalah asam sulfat. Model memakai pendekatan larutan asam; pelepasan proton bertahap tidak dimodelkan lengkap.",
  acetic: "Cuka mengandung asam asetat, asam lemah. Bandingkan pembacaan pH dengan asam kuat pada konsentrasi yang sama.",
  naoh01: "NaOH 0,1 M adalah larutan basa kuat. Gunakan indikator atau pH meter untuk membandingkannya dengan larutan asam.",
  naoh1: "NaOH 1 M lebih pekat daripada NaOH 0,1 M. Bandingkan pH sebelum dan sesudah menambahkan air.",
  ammonia: "NH₃ dalam air bersifat basa lemah. Bandingkan pH dengan NaOH dan amati pengaruh pengenceran.",
  h2o2: "H₂O₂ adalah hidrogen peroksida. Model mendukung penguraian dengan katalis tertentu; amati apakah gas terbentuk.",
  nacl: "NaCl adalah garam yang larut dalam air. Bandingkan daya hantar larutannya dengan air dan larutan gula.",
  kcl: "KCl adalah garam kalium yang larut dalam air. Coba pelarutan dan pembacaan daya hantar relatif.",
  cacl2: "CaCl₂ adalah garam kalsium yang dapat larut dalam air. Amati suhu dan sifat larutan setelah pencampuran.",
  licl: "LiCl adalah garam litium. Gunakan larutannya untuk mengeksplorasi daya hantar atau model uji nyala yang didukung.",
  na2co3: "Na₂CO₃ adalah natrium karbonat. Pelajari sifat basa larutannya dan perubahan saat bertemu asam.",
  nahco3: "NaHCO₃ adalah soda kue. Coba campurkan dengan cuka virtual dan amati pembentukan gas.",
  cuso4: "CuSO₄ adalah tembaga(II) sulfat. Larutkan dalam air untuk mengeksplorasi warna, pertukaran logam, atau model elektrolisis tembaga.",
  fecl3: "FeCl₃ adalah besi(III) klorida. Gunakan untuk mengeksplorasi perubahan warna atau pembentukan endapan yang didukung model.",
  agno3: "AgNO₃ adalah perak nitrat. Larutannya dapat dipakai untuk mengeksplorasi model endapan dengan ion klorida.",
  bacl2: "BaCl₂ adalah barium klorida. Model mendukung pengamatan endapan dengan sulfat; bahan nyata beracun.",
  pbno3: "Pb(NO₃)₂ adalah timbal(II) nitrat. Model mendukung pengamatan endapan dengan iodida; senyawa timbal nyata beracun.",
  ki: "KI adalah kalium iodida. Larutannya dapat dipakai untuk mengeksplorasi reaksi endapan yang melibatkan ion iodida.",
  kscn: "KSCN adalah kalium tiosianat. Coba model perubahan warna saat dicampur dengan larutan besi(III).",
  kno3: "KNO₃ adalah kalium nitrat. Bandingkan pelarutan pada suhu berbeda dan amati sisa padatan saat larutan jenuh.",
  na2so4: "Na₂SO₄ adalah natrium sulfat. Larutannya dapat menjadi sumber sulfat pada model reaksi endapan.",
  znso4: "ZnSO₄ adalah seng sulfat. Gunakan untuk mengeksplorasi larutan garam dan model reaksi logam yang didukung.",
  mg: "Pita Mg adalah logam magnesium. Amati perubahan pada model reaksi logam dengan asam; jangan mencoba pembakaran nyata.",
  zn: "Zn keping adalah logam seng. Bandingkan reaksinya dengan Zn serbuk pada jumlah yang sama.",
  "zn-powder": "Zn serbuk memiliki luas permukaan lebih besar daripada keping. Bandingkan laju model reaksi dengan asam.",
  cu: "Kawat Cu adalah logam tembaga. Gunakan untuk mengeksplorasi pertukaran logam atau pasangan elektroda pada model yang didukung.",
  fe: "Paku Fe adalah logam besi. Coba model pertukaran logam dengan larutan CuSO₄ dan amati perubahan yang tercatat.",
  al: "Al foil adalah aluminium. Lapisan oksida dan perilaku permukaan logam nyata belum dimodelkan lengkap.",
  ag: "Ag adalah logam perak. Bandingkan dengan logam lain; tidak setiap pasangan bahan memiliki reaksi dalam model.",
  caco3: "CaCO₃ keping adalah kalsium karbonat. Bandingkan pembentukan gas dalam asam dengan versi serbuk.",
  "caco3-powder": "CaCO₃ serbuk memiliki luas permukaan lebih besar daripada keping. Bandingkan laju reaksi dengan asam.",
  mno2: "MnO₂ dapat menjadi katalis pada model penguraian H₂O₂. Bandingkan hasil dengan dan tanpa katalis.",
  sand: "Pasir menjadi padatan tak larut untuk mencoba pengendapan dan penyaringan campuran.",
  "iron-powder": "Serbuk besi menjadi sampel untuk mencoba pemisahan magnetik dari campuran pasir.",
  sucrose: "Sukrosa adalah gula pasir. Bandingkan kelarutan dan daya hantar larutannya dengan larutan garam.",
  glucose: "Glukosa adalah gula pereduksi. Gunakan untuk mengeksplorasi model uji Benedict atau fermentasi.",
  starch: "Amilum adalah pati. Coba model uji iodin dan perubahan setelah perlakuan amilase.",
  yeast: "Ragi digunakan pada model fermentasi gula. Amati perubahan seiring waktu dan gas yang tercatat.",
  protein: "Putih telur adalah sampel protein untuk mengeksplorasi model uji biuret dan pengaruh pemanasan.",
  saliva: "Air liur / amilase menjadi contoh enzim pemecah amilum. Laju model bukan prediksi untuk sampel manusia nyata.",
  cabbage: "Kubis ungu menjadi contoh sumber pigmen indikator alami. Gunakan ekstrak kubis ungu bila ingin menguji warna indikator secara langsung.",
  dye: "Pewarna makanan / tinta menjadi sampel model kromatografi. Pigmen dan nilai Rf bersifat ilustratif.",
  soap: "Sabun membantu mengeksplorasi emulsi minyak dan air. Bandingkan lapisan sebelum dan sesudah pengadukan.",
  universal: "Indikator universal memberi perubahan warna untuk memperkirakan sifat asam atau basa. Gunakan pH meter untuk angka model.",
  pp: "Fenolftalein adalah indikator asam-basa. Bandingkan warna dalam larutan asam dan basa; warna bukan pembacaan pH tepat.",
  mo: "Metil oranye adalah indikator asam-basa dengan rentang perubahan warna berbeda dari fenolftalein.",
  btb: "Bromtimol biru adalah indikator asam-basa. Bandingkan warnanya dalam larutan asam, mendekati netral, dan basa.",
  "cabbage-indicator": "Ekstrak kubis ungu menjadi indikator alami. Bandingkan warna pada larutan asam dan basa.",
  iodine: "Larutan iodin digunakan untuk mengeksplorasi model uji amilum. Bandingkan sampel yang mengandung pati dengan air.",
  benedict: "Pereaksi Benedict digunakan untuk model uji gula pereduksi. Pilih sampel dan amati syarat pemanasan pada model.",
  biuret: "Pereaksi biuret digunakan untuk model uji protein. Bandingkan putih telur dengan sampel tanpa protein.",
};

export const chemistryMaterialGuides: Record<string, EquipmentGuide> = Object.fromEntries(
  chemistryMaterials.filter(material => descriptions[material.id]).map(material => [material.id, {
    purpose: descriptions[material.id],
    usage: material.phase === "solid"
      ? `Ambil ${material.name} dari rak Bahan. Seret ke wadah, atau pilih bahan, wadah tujuan, dan jumlah dalam gram lalu tekan Tuang / campur. Pilih wadah untuk mengamati hasilnya.`
      : `Ambil ${material.name} dari rak Bahan. Seret ke wadah, atau pilih bahan, wadah tujuan, dan jumlah dalam mL lalu tekan Tuang / campur. Menaruh botol di meja belum menuangkan isinya.`,
    limitation: "Hanya kombinasi yang didukung model menghasilkan reaksi. Tidak ada perubahan bukan bukti bahwa campuran nyata aman atau tidak reaktif. Semua percobaan ini hanya simulasi.",
  }]),
);
