import assert from "node:assert/strict";
import { renderToStaticMarkup } from "react-dom/server";
import { initialLab, reduceLab } from "../../../lib/sandbox/engine";
import { Shape } from "../../../components/sandbox/Shape";
import { chemistryVisualEffects } from "../visualEffects";
import { pourDrop } from "../drop";

let state = reduceLab(initialLab(), { type: "add", material: "beaker" });
const id = state.entities[0].id;
state = pourDrop(state, id, { material: "water" })!.state;
const vessel = state.entities[0];
assert.deepEqual(chemistryVisualEffects(vessel, state), { bubbles: false, steam: false });
vessel.temperature = 100;
assert.deepEqual(chemistryVisualEffects(vessel, state), { bubbles: true, steam: true });
const boiling = renderToStaticMarkup(<Shape entity={vessel} state={state} />);
assert.ok(boiling.includes('class="chemistry-bubble"') && boiling.includes('class="chemistry-steam"'));
vessel.sealed = true;
assert.equal(chemistryVisualEffects(vessel, state).steam, false);
vessel.temperature = 25;
vessel.gas = 1;
assert.equal(chemistryVisualEffects(vessel, state).bubbles, false, "Accumulated gas is not proof of an ongoing reaction");
state.events.push({ id: 99, time: state.time, type: "gas.formed", entity: id, message: "Gas terbentuk" });
assert.equal(chemistryVisualEffects(vessel, state).bubbles, true);
state.time += 2;
assert.equal(chemistryVisualEffects(vessel, state).bubbles, false);
vessel.contents = [];
vessel.temperature = 100;
assert.deepEqual(chemistryVisualEffects(vessel, state), { bubbles: false, steam: false });
state = reduceLab(state, { type: "add", material: "burner" });
const burner = state.entities.at(-1)!;
assert.ok(!renderToStaticMarkup(<Shape entity={burner} state={state} />).includes('class="chemistry-flame"'));
burner.active = true;
assert.ok(renderToStaticMarkup(<Shape entity={burner} state={state} />).includes('class="chemistry-flame"'));
console.log("Chemistry visual-effects checks passed: quiet cold water, boiling/gas bubbles, open-vessel steam, no dry-vessel effects and active flame.");
