import { Material } from "../../lib/sandbox/types";

const apparatus: [string, string, string][] = [
  ["block", "Balok", "incline"],
  ["ball", "Bola", "fall"],
  ["cart", "Troli dinamik", "newton"],
  ["incline", "Bidang miring", "incline"],
  ["pulley", "Katrol + tali", "newton"],
  ["spring", "Pegas", "spring"],
  ["pendulum", "Bandul", "pendulum"],
  ["spring-balance", "Neraca pegas", "buoyancy"],
  ["ruler", "Mistar", "length"],
  ["launcher", "Meriam proyektil", "projectile"],
  ["surface", "Meja licin / kasar / karpet", "friction"],
  ["fluid-vessel", "Bejana fluida", "buoyancy"],
  ["wood", "Kayu", "buoyancy"],
  ["ice", "Es", "phase"],
  ["iron", "Besi", "buoyancy"],
  ["aluminium", "Aluminium", "buoyancy"],
  ["copper", "Tembaga", "buoyancy"],
  ["plastic", "Plastik", "buoyancy"],
  ["cork", "Gabus", "buoyancy"],
  ["heater", "Pemanas listrik", "heat"],
  ["communicating-vessels", "Bejana berhubungan", "hydrostatic"],
  ["u-tube", "Pipa U", "hydrostatic"],
  ["battery", "Baterai / catu daya", "circuit"],
  ["lamp", "Lampu pijar", "circuit"],
  ["resistor", "Resistor", "circuit"],
  ["switch", "Saklar", "circuit"],
  ["wire", "Kabel", "circuit"],
  ["fuse", "Sekring", "circuit"],
  ["ammeter", "Amperemeter", "current"],
  ["voltmeter", "Voltmeter", "voltage"],
  ["multimeter", "Multimeter", "current"],
  ["capacitor", "Kapasitor", "rc"],
  ["led", "LED", "led"],
  ["rheostat", "Rheostat", "circuit"],
  ["magnet", "Magnet batang", "magnet"],
  ["coil", "Kumparan", "induction"],
  ["compass", "Kompas", "magnet"],
  ["galvanometer", "Galvanometer", "induction"],
  ["light", "Sumber cahaya", "snell"],
  ["screen", "Layar", "lens"],
  ["convex-lens", "Lensa cembung", "lens"],
  ["concave-lens", "Lensa cekung", "lens"],
  ["plane-mirror", "Cermin datar", "reflection"],
  ["concave-mirror", "Cermin cekung", "lens"],
  ["convex-mirror", "Cermin cembung", "lens"],
  ["prism", "Prisma kaca", "dispersion"],
  ["glass-block", "Balok kaca / air", "snell"],
  ["slit", "Celah", "wave"],
  ["slinky", "Tali / slinky", "wave"],
  ["tuning-fork", "Garpu tala", "sound"],
  ["sound-source", "Sumber bunyi", "sound"],
  ["oscilloscope", "Osiloskop", "wave"],
  ["collision", "Dua troli tumbukan", "collision"],
  ["metal-rod", "Batang pemuaian", "expansion"],
  ["black-white", "Permukaan hitam / putih", "radiation"],
];

export const physicsCatalog = apparatus.map(([id, name, model]): Material => ({
  id, name, model,
  kind: ["current", "voltage", "length"].includes(model) ? "instrument" : "apparatus",
  discipline: "physics",
}));
